name: Node.js CI

on:
  push:
    branches: [main, release/**]
  pull_request:
    branches: [main, release/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Save build assets
        uses: actions/upload-artifact@v4
        with:
          name: lib-folders
          path: packages/*/lib
          retention-days: 1

  checks:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Load build assets
        uses: actions/download-artifact@v4
        with:
          name: lib-folders
          path: packages

      - name: Check formatting
        run: pnpm run format:check

      - name: Check types
        run: pnpm run check-types

      - name: Lint
        run: pnpm run lint

  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Load build assets
        uses: actions/download-artifact@v4
        with:
          name: lib-folders
          path: packages

      - name: Run tests
        run: pnpm run test
