name: Node.js CI

on:
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main, release/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Check formatting
        run: pnpm run format:check

      - name: Archive build assets
        run: tar cvf build-result.tar packages/*/cjs

      - name: Save build assets
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: build-result.tar
  test:
    strategy:
      matrix:
        node-version: [ 20, 22, 23 ]

    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: pnpm install

      - name: Load build assets
        uses: actions/download-artifact@v4
        with:
          name: build-result

      - name: Unarchive build assets
        run: tar xvf build-result.tar

      - run: pnpm run test
